"""empty message

Revision ID: 19a7dfdbbbd1
Revises: 13b7404738c4
Create Date: 2019-09-13 13:48:45.312249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a7dfdbbbd1'
down_revision = '13b7404738c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('duration_end', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('duration_start', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('image_url', sa.String(length=200), nullable=False))
    op.add_column('events', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('time', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'events', 'users', ['organizer_id'], ['id'])
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('img_url', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.add_column('users', sa.Column('updated_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('user_name', sa.String(length=80), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'updated_date')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'img_url')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'created_date')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'time')
    op.drop_column('events', 'price')
    op.drop_column('events', 'organizer_id')
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'duration_start')
    op.drop_column('events', 'duration_end')
    op.drop_column('events', 'address')
    # ### end Alembic commands ###
